---
title: "Assigment - Data Driven Decision Making V3"
author: "Luc Heimans"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

Search Youtube for a suitable business case example on data driven decision making and copy the embed code below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/6GZzrugo8rY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>

## Why was data driven decision making (3DM) useful in this business case?

Overall, Netflix provides an improved personalized customer experienced based on data analytics and decision making. (5 minutes learning, 2021). 

## How did the organization apply 3DM?

Netflix has multiple uses of data analytics to make business decisions based on data:

- Link prediction (recommendations of videos after watching one based on content-based filtering (see figure 1))
- Regression (determine a numerical value on how much someone is likely to watch a different show, based on historical consumer data)
- Profiling (they make up a typical profile of groupings to determine what features a new show should have so that the profiles of the mass would like the show (based on the available data)) An example of such show is House of Cards (5 minutes learning, 2021).
- Success rate prediction of shows. Netflix predicts the success rate of shows based on data analytics to give shape to shows (house of cards). This success rate is said to have led to 80% of Netflix shows being a 'success' according to 5 minutes learning, 2021. This predicament of a success rate has also led to helping Netflix decrease promotional activities and campaigns.
- Co-occurence grouping. Someone watches show A after finishing show B. Another person watches show B and finishes it. Netflix then recommends show A to the other person based on what the first person watched in combination with show A.This data mining methodology is displayed under collaborative filtering in figure 1. 

## What can the organization do with 3DM that they couldn’t do before?

- Create a success rate for shows. The rate is created through creating algorithms (data mining) (5 minutes learning, 2021). 
- Improve the personalized customer experience.
- Make shows in a way that they are conform the wants of the customer.





########### Business case 2

---
title: "Assigment - Data Problems vs Data Solutions"
author: "Luc Heimans"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

Search Youtube for a suitable business case example on data driven decision making and copy the embed code below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/SEXLD02Fw6U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>


## What was the business problem?

Airbnb wanted to make a comparative analysis on the price and listing trends of LA and NY from october 2018 to october 2019 to spot differences between the two and bring them more close to each other. 


## How was it translated into a data mining problem?

The business problems, formulated into data mining problems, are then:
- Are there differences in distributions of listing property sizes between LA and NY?
- Are there differences in city average price trends throughout the year?
- Are there differences in price spikes around weekends?

The overall process followed the CRISP DM model. This means firstly the business problem was stated, out of the business problem, data mining problems were formulated. The data mining problems are formulated in a way where you can answer them by analyzing/ modelling the available data.

## What is the realized business value?

The difference in low-price listings in the weekend turned out to be statistically significant between LA and NY. For high-price listings this was not the case.

The analysis and data mining outcome helped in price based decision making  from the host their view (SQL Data Ninja, 2020) as the conclusions offered insight into the difference in pricings of both locations and enabled decision making to decrease the price differences between LA and NY.

SQL Data Ninja, 2020, Retrieved 09/03/2021 from: "https://www.youtube.com/embed/SEXLD02Fw6U"




########### Business case 3

---
title: "Assigment - Data Driven Business"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

<iframe width="560" height="315" src="https://www.youtube.com/embed/QlqI0gGOjo4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>


## What features define a data driven business?

Features that define a data driven business based on the Shell case study by Bernard Marr (2020):
- Making strategic decision based on data 
- Linking data to the measurement of KPI's
- Seeing data as an equally important in an organization as departements such as finance and/or marketing/sales.

## What are the important features of a data culture?

- The data quality and standards
- Linking data to the business effectively, so for example to inform KPI' or by creating metrics related to data and business.Also, using data marts effectively to make sure only data which has business value is used in stead of using all data available as this has scaling problems and can turn data into a liability (Dan Jeavons, 2020).
Having a professional data management process and corresponding high-quality technology which supports the scaling of data.
- The quality of the data scientists and engineers which work with the data on a daily basis.
- Having not only people who speak the language of data science but also having people who speak the language of both data science and business.These people are called business translators according to Dan Jeavons (2020) and are vital in a data culture.

## What are the transformation steps towards a mature data driven business?

- An important step is to identify a data strategy. Also, make the data strategy as important as the business.
- Also, do not try to reinvent the wheel but try to leverage best practices externally,this could be from other companies or even industries. 
- Moreover, try to link the data usage closely to the business' needs, KPI's and so forth because it is very easy to start working with data without extracting value from it.
- A two-speed approach can be taken. Such approach means that processes and software are refreshed quickly and frequently (Sven Blumberg et al, 2016). According to Sven Blumberg et al (2016), such approach can ensure a company stays on the fast track and thus maintains a (high) competitive advantage. Also, a two speed approach mitigates risk since platforms are frequently refreshed and updated, making less of a need for big changes in the long-term which often cause hazzard (Sven Blumberg et al, 2016). Transforming a business into a more mature digital organization is a complex matter and by using a two speed approach, this transition can be managed and scaled (Sven Blumberg at al, 2016).
- creating a highly professional environment for data scientists and engineers to function in.


## references

Blumberg, S., Bossert, O., & Laartz, J. (2020, February 13). Deploying a two-speed architecture at scale. McKinsey & Company. Retrieved 25/03/2-21 from https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/deploying-a-two-speed-architecture-at-scale

Bernard Marr, 2020, Retrieved 25/03/2021 from: "https://www.youtube.com/embed/QlqI0gGOjo4"




